apiVersion: v1
kind: Service
metadata:
  name: electronics-shop-service
  labels:
    app: electronics-shop
spec:
  selector:
    app: electronics-shop
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80 # The port the service will listen on (standard HTTP)
      targetPort: 8000 # The port on the container that the service will forward traffic to
