# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
  namespace: my-secure-app
spec:
  selector:
    app: my-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP