apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespace-labeler-role
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch", "update", "patch"] 
- apiGroups: [""]
  resources: ["namespaces/status"]
  verbs: ["get"] 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: namespace-labeler-rolebinding
subjects:
- kind: ServiceAccount
  name: default
  namespace: my-controller-system
roleRef:
  kind: ClusterRole
  name: namespace-labeler-role
  apiGroup: rbac.authorization.k8s.io